source "https://rubygems.org"

gem "sinatra"
gem "sinatra-contrib"
gem "pry-byebug"
gem "better_errors"
gem "binding_of_caller"
gem "smarter_csv"
gem "sinatra-flash"
gem "activerecord"
gem "sinatra-activerecord"
gem "rake"
gem "pg"